version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=database
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge



# version: "3.8"

# services:
#   mysqldb:
#     image: mysql:5.7
#     networks:
#       - employee-mysql
#     restart: always
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#       - MYSQL_DATABASE=$MYSQLDB_DATABASE
#       - MYSQL_PASSWORD=$MYSQL_PASSWORD
#     ports:
#       - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#     volumes:
#       - db:/var/lib/mysql
#   app:
#     depends_on:
#       - mysqldb
#     build: .
#     networks:
#       - employee-mysql
#     restart: on-failure
#     env_file: ./.env
#     ports:
#       - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#     environment:
#       SPRING_APPLICATION_JSON: '{
#         "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false",
#         "spring.datasource.username" : "$MYSQLDB_USER",
#         "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#         "spring.jpa.hibernate.ddl-auto" : "update"
#       }'
#     volumes:
#       - .m2:/root/.m2
#     stdin_open: true
#     tty: true

# volumes:
#   db:
# networks:
#   employee-mysql:
