name: Java CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build action
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack
        run: |
          echo ---Building and starting up docker---
          docker-compose -f docker-compose.yml up -d --build
          sleep 120 
          echo ---Containers up---

      - name: Check running containers
        run: docker ps

          
  test:
    name: Test action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down    
