name: Java CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build action
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack
        run: |
          echo ---Building and starting up docker---
          docker-compose -f "docker-compose.yml" up -d --build
          echo ---Containers up---
 

      - name: Check running containers
        run: docker ps

          
  # test:
  #   name: Unit Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Set up JDK 8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 8
  #     - name: Maven Package
  #       run: |
  #         sleep 120
  #         mvn -B clean package -DskipTests
  #     - name: Maven Verify
  #       run: mvn -B clean verify
  #     - name: Stop containers
  #       if: always()
  #       run: docker-compose -f "docker-compose.yml" down    